name: HACS Action

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - name: HACS Action
        uses: hacs/action@d556e736723344f83838d08488c983a15381059a # 22.5.0
        with:
          category: "integration"
